version: '3.8'

services:
  calculator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - PORT=8080
      - LOG_LEVEL=DEBUG
      - SECRET_KEY=dev-secret-key-for-docker
      - METRICS_ENABLED=true
    volumes:
      - ./app:/app/app:ro
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped