apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: calculator-app-np
  namespace: calculator-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: calculator-app
  type: NodePort