apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: calculator-app-np
  namespace: calculator-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: calculator-app
  type: NodePort